apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: inventory

data:
  SERVER_PORT: "3000"
  HOST: 0.0.0.0
  SALT_ROUNDS: "10"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "inventory_db"
  FRONTEND_URL: "http://inventory.local"